name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Run pipeline on push to main

jobs:
  build:
    runs-on: ubuntu-latest  # Runner machine

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Get the code

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2  # Setup Terraform CLI
        with:
          terraform_version: 1.6.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
